### ISSUE TITLE
feat(app): rebase the working branch automatically

### ISSUE THREAD

**Issue by hasundue** [hasundue/denopendabot#1010]

**Comment by kamekyame** [comment]
Do you mean to avoid creating a new PR when updating?

**Comment by hasundue** [comment]
Sorry for lack of description 😅 

I mean, when the main branch is updated, `denopendabot` branch should be rebased to the main branch. An open PR should be also updated if exists.

**Comment by kamekyame** [comment]
I see.

If a PR has already been created, denopendabot closes the old PR and creates a new one, is this intended?
If denopendabot does rebase when the main branch changes, it will update the existing PR.

**Comment by hasundue** [comment]
> If a PR has already been created, denopendabot closes the old PR and creates a new one, is this intended?

Not intended, honestly. This is actually kinda annoying, so maybe we'll fix the behavior so that denopendabot just re-push the working branch.
