### ISSUE TITLE
I wish `deno.lock` to be ignored by default

### ISSUE THREAD

**Issue by arrow2nd** [hasundue/denopendabot#1273]
Thanks for the great tool.

I just added denopendabot to my project and noticed that it is trying to update up to `deno.lock`.
> ref: https://github.com/arrow2nd/morino/actions/runs/3566059788/jobs/5992019527

This can be excluded by setting the option `exclude: deno.lock`.

However, I think it would be easier to use if it were excluded by default, since there is no need to modify `deno.lock`, at least in updating dependencies.

What do you think?

**Comment by hasundue** [comment]
Sure, I'll work on it soon.
Thanks for trying out Denopendabot!
