### ISSUE TITLE
Getting `Error: Resource not accessible by integration` after adding `denopendabot.yml`

### ISSUE THREAD

**Issue by yardenshoham** [hasundue/denopendabot#1795]
I added the GitHub app but it didn't send a PR to add `denopendabot.yml` so I created it myself. I then tried to run it and the output was `Error: Resource not accessible by integration`.

Here's the run https://github.com/yardenshoham/gitea-backporter/actions/runs/4082757846
![image](https://user-images.githubusercontent.com/20454870/216562953-b7f18674-b564-4f83-a435-85e3ded975ca.png)

**Comment by yardenshoham** [comment]
I'll use it as an action

**Comment by yardenshoham** [comment]
Fixed by #1798?

**Comment by hasundue** [comment]
Yes!
