### ISSUE TITLE
Proposal: Don't create a branch if there's no need

### ISSUE THREAD

**Issue by yardenshoham** [hasundue/denopendabot#1796]
Denopendabot should only create a branch on remote if it's going to open a PR; otherwise, it's just clutter. I can implement this and send a PR if the proposal is accepted.

**Comment by yardenshoham** [comment]
Has this project been abandoned? @hasundue

**Comment by hasundue** [comment]
Sorry I've been sick and unable to work.
I agree with your proposal and a PR would be appreciated.
