### ISSUE TITLE
Feature request: accept glob to exclude

### ISSUE THREAD

**Issue by Omochice** [hasundue/denopendabot#2296]
## Summary 

`exclude` option accept glob too.

## Background

I use this app on my blog repository.

When I run CI. I notice denopendabot try to update import statement in markdown file: https://github.com/Omochice/blog/actions/runs/5757305813/job/15608168133

I dont want to update import statement in blog post. So, I try `exclude` option.
But listing all blog post path is not maintainable.

Currently `exclude` option seems to accept only simple path string.
I think it would be useful to be able to use glob patterns.

How do you think?

**Comment by hasundue** [comment]
Sounds good, and thanks for a PR!
I'm taking a look soon.
